# Generated by Django 5.1.4 on 2025-03-31 11:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=30)),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateField()),
                ('numero_recu', models.CharField(max_length=12)),
                ('mode_paiement', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=45)),
                ('motif_edition', models.CharField(max_length=200)),
                ('date_archive', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=20)),
                ('cycle', models.CharField(choices=[('Premier', '1er Cycle'), ('Second', '2end Cycle')], max_length=30)),
                ('frais_inscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensualite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tranche1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tranche2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tranche3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_scolarite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('non_inscrit', 'Non Inscrit'), ('inscrit', 'Inscrit'), ('termine', 'Terminé')], default=('non_inscrit', 'Non Inscrit'), max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('inscriptions', 'Inscription'), ('mensuel', 'Mensuel'), ('tranche1', '1er Tranche'), ('tranche2', '2nd Tranche'), ('Annuel', 'Annuel')], max_length=30)),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('numero_recu', models.CharField(max_length=12)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espece'), ('virement', 'Virement')], max_length=20)),
                ('reference', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='School_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('libelle', models.CharField(max_length=12)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('cloturee', 'Cloturée')], default='Active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('masculin', 'M'), ('feminin', 'F')], max_length=12)),
                ('parent_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
