# Generated by Django 6.0 on 2026-02-13 07:38

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_Scolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('libelle', models.CharField(max_length=12)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('cloturee', 'Cloturée')], default='Active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=20)),
                ('cycle', models.CharField(choices=[('Premier', '1er Cycle'), ('Second', '2end Cycle')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('masculin', 'M'), ('feminin', 'F')], max_length=12)),
                ('parent_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('localisation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('motif', models.CharField(max_length=30)),
                ('date_depense', models.DateField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('normal', 'Normal'), ('exonoré', 'Exoneré')], default='Exoneré', max_length=50)),
                ('statut', models.CharField(choices=[('non_inscrit', 'Non Inscrit'), ('inscrit', 'Inscrit'), ('termine', 'Terminé')], default='Non Inscrit', max_length=125)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.annee_scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'classe', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='FraisInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_remise', models.CharField(blank=True, max_length=200)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.inscription')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.typefrais')),
            ],
            options={
                'unique_together': {('inscription', 'type_frais')},
            },
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('numero_recu', models.CharField(max_length=12)),
                ('annule', models.BooleanField(default=False)),
                ('frais_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.fraisinscription')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
