# Generated by Django 5.1.4 on 2025-03-31 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archive_payment',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.formation'),
        ),
        migrations.AddField(
            model_name='archive_payment',
            name='inscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.inscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.inscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archive_payment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='caisse.payment'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.school_year'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.student'),
        ),
    ]
