# Generated by Django 6.0 on 2026-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
