# Generated by Django 6.0 on 2026-02-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_typefrais_ordre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('ANNULATION', 'Annulation'), ('REMlSE', 'Remise'), ('PAIEMENT', 'Paiement')], max_length=30)),
                ('modele', models.CharField(max_length=100)),
                ('objet_id', models.PositiveIntegerField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True)),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
