# Generated by Django 5.1.4 on 2025-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='regime',
            field=models.CharField(choices=[('exonoré', 'Exoneré'), ('normal', 'Normal')], default='Normal', max_length=50),
        ),
    ]
