# Generated by Django 5.1.4 on 2025-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_inscription_regime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='tranche1',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='tranche2',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='tranche3',
        ),
        migrations.AddField(
            model_name='formation',
            name='frais_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='formation',
            name='nbre_mois',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='frais_scolarite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
