# Generated by Django 5.1.4 on 2025-05-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_remove_formation_tranche1_remove_formation_tranche2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='pourcentage',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='regime',
            field=models.CharField(choices=[('', ''), ('normal', 'Normal'), ('exonoré', 'Exoneré')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='motif',
            field=models.CharField(choices=[('inscriptions', 'Inscription'), ('mensuel', 'Mensuel'), ('Annuel', 'Annuel')], max_length=30),
        ),
    ]
