# Generated by Django 5.1.4 on 2025-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_inscription_pourcentage_alter_inscription_regime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='regime',
            field=models.CharField(choices=[('normal', 'Normal'), ('exonoré', 'Exoneré')], default='Exoneré', max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('non_inscrit', 'Non Inscrit'), ('inscrit', 'Inscrit'), ('termine', 'Terminé')], default='Non Inscrit', max_length=125),
        ),
    ]
