# Generated by Django 5.2.5 on 2025-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='intendent',
            new_name='is_caissier',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_censeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_comptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_informaticien',
            field=models.BooleanField(default=False),
        ),
    ]
