# Generated by Django 6.0 on 2026-03-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_rename_intendent_utilisateur_is_caissier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_caissier',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_censeur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_comptable',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_informaticien',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('PROVISEUR', 'Proviseur'), ('COMPTABLE', 'Comptable'), ('CAISSIER', 'Caissier'), ('SECRETAIRE', 'Secrétaire')], default='SECRETAIRE', max_length=20),
        ),
    ]
